heat_template_version: 2014-10-16

description: |
  This template deploys the security resources for the stack

resources:
  frontend_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: allow incoming SSH and ICMP and HTTP traffic from anywhere.
      name:
        list_join:
          ["-", [{ get_param: "OS::stack_name" }, "frontend_security_group"]]
      rules:
        - {
            direction: ingress,
            remote_ip_prefix: 0.0.0.0/0,
            port_range_min: 22,
            port_range_max: 22,
            protocol: tcp,
          }
        - {
            direction: ingress,
            remote_ip_prefix: 0.0.0.0/0,
            port_range_min: 8080,
            port_range_max: 8080,
            protocol: tcp,
          }
        - { direction: ingress, remote_ip_prefix: 0.0.0.0/0, protocol: icmp }

  backend_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: allow incoming PostgreSQL traffic from private network.
      name:
        list_join:
          ["-", [{ get_param: "OS::stack_name" }, "backend_security_group"]]
      rules:
        - {
            direction: ingress,
            remote_ip_prefix: 0.0.0.0/0,
            port_range_min: 22,
            port_range_max: 22,
            protocol: tcp,
          }
        - {
            direction: ingress,
            remote_ip_prefix: 10.1.0.0/24,
            port_range_min: 3306,
            port_range_max: 3306,
            protocol: tcp,
          }

  nfs_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: allow incoming NFS traffic from private network.
      name:
        list_join:
          ["-", [{ get_param: "OS::stack_name" }, "nfs_security_group"]]
      rules:
        - {
            direction: ingress,
            remote_ip_prefix: 0.0.0.0/0,
            port_range_min: 22,
            port_range_max: 22,
            protocol: tcp,
          }
        - {
            direction: ingress,
            remote_ip_prefix: 10.1.0.0/24,
            port_range_min: 2049,
            port_range_max: 2049,
            protocol: tcp,
          }
        - {
            direction: ingress,
            remote_ip_prefix: 10.1.0.0/24,
            port_range_min: 2049,
            port_range_max: 2049,
            protocol: udp,
          }
        - { direction: ingress, remote_ip_prefix: 0.0.0.0/0, protocol: icmp }

outputs:
  frontend_security_group:
    description: Security group to use for the frontend instance
    value: { get_resource: frontend_security_group }
  backend_security_group:
    description: Security group to use for the backend instance
    value: { get_resource: backend_security_group }
  nfs_security_group:
    description: Security group to use for the NFS instance
    value: { get_resource: nfs_security_group }
