- name: Create an ssh security group
  openstack.cloud.security_group:
    state: present
    name: ansible-ssh
    description: security group for ssh

- name: Create a security group rule for ssh
  openstack.cloud.security_group_rule:
    security_group: ansible-ssh
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
